### ISSUE TITLE
Subpixel alignment of vertical lines in GUI apps

### ISSUE THREAD

**Issue by silverwind** [Alhadis/Menloco#4]
When edge characters like `┐` and `│` meet, I see this alignment issue:

<img width="108" alt="screen shot 2018-02-25 at 11 46 31" src="https://user-images.githubusercontent.com/115237/36640560-98d585d2-1a21-11e8-93d6-d91e8f1dbde1.png">

The issue shows for me on macOS in Firefox, Chrome, Sublime Text and Atom, but interestingly not in iTerm. The original Menlo font does not show this issue:

<img width="103" alt="screen shot 2018-02-25 at 11 57 34" src="https://user-images.githubusercontent.com/115237/36640632-19ec8034-1a23-11e8-961f-bc6b2cd309d6.png">

Here's the example text:
````
 ┌─────────┐
 │  Lorem  │
 │  ipsum  │
 │dolor sit│
 │  amet,  │
 │consectet│
 └─────────┘
````

**Comment by silverwind** [comment]
Looks like the issue is even present on single characters. Here's the vertical beam in Chrome:

<img width="157" alt="screen shot 2018-02-25 at 12 52 44" src="https://user-images.githubusercontent.com/115237/36641113-e915cd78-1a2a-11e8-9f46-5d6ef90b8254.png">

This is so weird. The character is vertical beam in the font file, at least according to FontForge:

<img width="625" alt="screen shot 2018-02-25 at 12 54 14" src="https://user-images.githubusercontent.com/115237/36641124-0352a83c-1a2b-11e8-9f67-8a59c2cac83b.png">

**Comment by Alhadis** [comment]
That'll be because Menlo and Monaco use two different advance widths for their characters, which matters only when applications consider proportional sizing in font rendering. So in other words:

~~~
┌─────────┐ <- This row looks fine, because it only uses Menlo glyphs
│  Lorem  │ <- This row looks screwed, because it uses glyphs from
               both Menlo and Monaco
~~~

So as far as font metrics are concerned, you may as well have two completely different typefaces in use in the editor. If Menlo's advance widths are stored internally at, say, 1000, and Monaco's are 1004 or what-have-you, there's inevitably going to be a discrepancy when glyphs are mixed in a medium that *isn't* fixed-pitch.

This isn't easy to fix programmatically, I'm afraid. :disappointed:

Of course, if both fonts *weren't* commercial, I'd simply hack them together in an editor and upload the manually-corrected version. :grinning: But since they're proprietary, I had to write this entire repository just to share my work with the world.

Fuck closed-source.

**Comment by Alhadis** [comment]
Oh, and I was planning on making a similar repository to share my patched version of Menlo called Menlig (Menlo + ligatures), but I lost the source files with my MacBook. I was lucky enough to recover the OTF for it.

Here's how it looks in Konsole and Atom, or anything which supports OpenType ligatures:

![screenshot_2018-02-25_22-26-11](https://user-images.githubusercontent.com/2346707/36641303-a96aeba2-1a81-11e8-89f1-0c4f4e4dfb24.png)

Which I've [uploaded here](https://github.com/Alhadis/.files/blob/master/share/desktop/Menlig.otf) because I've well and truly had it with Apple.

`/angry-diatribe-over`

**Comment by silverwind** [comment]
Thanks. I'm personally not that much into ligatures, but I can recommend the Fira Code font if you like them.

As for this issue: You're right. Monaco uses a advance width of `1233` while Menlo has `1229`, resulting in ever so slight misalignments. It might be possible to set the width of replaced glyphs to fix this issue, but I'm not sure if the font forge API (http://dmtr.org/ff.php) can do that.
